name: Secrets Scan
on:
  pull_request:
  push:
    branches: ['**']
permissions:
  contents: read
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: trufflesecurity/trufflehog-actions-scan@v0.19.0
        with:
          extra_args: --since-commit=$(git rev-list --max-parents=0 HEAD)
